export type AppliedKind = 'STICKER' | 'PATCH' | 'CHARM';

/** A sticker, patch or charm applied to an item. */
export interface AppliedItem {
  kind: AppliedKind;
  name: string;
  /**
   * The same piece as it is listed on the market, on its own: a Titan
   * applied to a rifle is `Sticker | Titan | Katowice 2014` in every
   * price list there is.
   *
   * Built here rather than in the browser. The rule is a Steam fact —
   * the kind is the first segment of the name — and a screen guessing at
   * it would ask for prices under names nothing recognises.
   */
  marketHashName: string;
  imageUrl: string | null;
  /** Slot, in the order Steam returns them. Starts at 0. */
  position: number;
  /**
   * Scrape level, from 0 (intact) to 1 (nearly gone). `null` when it could
   * not be determined safely — see `withScrape`.
   *
   * Two copies of the same sticker with different scrape levels are worth
   * different amounts, which is why applied items are never grouped by
   * name.
   */
  wear: number | null;
}

/**
 * Matches the scrape level from `asset_accessories` with the applied
 * items read from the HTML.
 *
 * These are two separate Steam sources for the same thing: the HTML
 * carries name and image but no scrape level; `asset_accessories` carries
 * the scrape level but identifies each piece only by `classid` — which
 * does not appear in `descriptions`, so the name cannot be resolved from
 * it.
 *
 * The only possible link is the order. That is why we only match when the
 * counts agree: pairing lists of different lengths would assign one
 * sticker's scrape level to another, and scrape level moves the price
 * directly — being wrong here is worse than showing nothing.
 *
 * Charms do not scrape and do not appear in `asset_accessories`, so they
 * stay out of the count.
 */
export function withScrape(
  applied: AppliedItem[],
  scrapeLevels: number[],
): AppliedItem[] {
  const scrapable = applied.filter((a) => a.kind !== 'CHARM');

  if (scrapable.length !== scrapeLevels.length) {
    return applied;
  }

  let i = 0;

  return applied.map((a) =>
    a.kind === 'CHARM' ? a : { ...a, wear: scrapeLevels[i++] },
  );
}

interface DescriptionBlock {
  name?: string;
  value?: string;
}

/**
 * Extracts what is applied to an item.
 *
 * Steam does not deliver this as structured data: it arrives as a block
 * of HTML inside `descriptions`, with one <img> per application. A real
 * example:
 *
 *   <div id="sticker_info" ...><center>
 *     <img ... src="https://.../titan.png" title="Sticker: Titan | Katowice 2014">
 *     <br>Sticker: Hello AK-47 (Gold), Titan | Katowice 2014
 *   </center></div>
 *
 * We read the <img> tags instead of the trailing text line for two
 * reasons: they carry the image, and the text separates names by comma —
 * which would break for any sticker whose name contains one.
 *
 * This is HTML parsing with a regular expression, normally a bad idea.
 * It is acceptable here because the HTML is generated by Steam in a fixed
 * shape, and the alternative would be pulling in a whole parser to read a
 * single tag. If Valve changes the format, the tests break — on purpose.
 */
export function extractApplied(
  blocks: DescriptionBlock[] | undefined,
): AppliedItem[] {
  if (!blocks?.length) {
    return [];
  }

  const applied: AppliedItem[] = [];

  for (const block of blocks) {
    if (!block.name || !block.value) {
      continue;
    }

    if (!APPLICATION_BLOCKS.has(block.name)) {
      continue;
    }

    for (const img of block.value.matchAll(IMG_TAG)) {
      const tag = img[0];
      const src = SRC_ATTRIBUTE.exec(tag)?.[1] ?? null;
      const title = TITLE_ATTRIBUTE.exec(tag)?.[1];

      if (!title) {
        continue;
      }

      // The title comes as "Sticker: Name", "Patch: Name" or
      // "Charm: Name". The prefix is the source of truth for the kind —
      // more reliable than the block name, which Valve has already
      // changed in the past (charms live in keychain_info but identify
      // themselves as "Charm").
      const separator = title.indexOf(':');

      if (separator === -1) {
        continue;
      }

      const prefix = title.slice(0, separator).trim();
      const kind = PREFIX_TO_KIND[prefix];

      if (!kind) {
        continue;
      }

      const name = decodeEntities(title.slice(separator + 1).trim());

      applied.push({
        kind,
        name,
        // From the kind, not from the prefix we just read: the prefix is
        // whatever Steam wrote in the title, and the market name has to
        // be one of exactly three words.
        marketHashName: `${KIND_TO_MARKET_PREFIX[kind]} | ${name}`,
        imageUrl: src,
        position: applied.filter((a) => a.kind === kind).length,
        // Filled in later from asset_accessories — see withScrape
        wear: null,
      });
    }
  }

  return applied;
}

const APPLICATION_BLOCKS = new Set([
  'sticker_info',
  'keychain_info',
  'patch_info',
]);

const PREFIX_TO_KIND: Record<string, AppliedKind> = {
  Sticker: 'STICKER',
  Patch: 'PATCH',
  Charm: 'CHARM',
};

/**
 * How the market names each kind. The same three words as above, but
 * kept apart on purpose: that map reads whatever Steam sends, this one
 * writes what the price lists expect, and they are only equal today.
 */
const KIND_TO_MARKET_PREFIX: Record<AppliedKind, string> = {
  STICKER: 'Sticker',
  PATCH: 'Patch',
  CHARM: 'Charm',
};

const IMG_TAG = /<img\b[^>]*>/g;

// Read separately from the tag so we do not depend on attribute order.
const SRC_ATTRIBUTE = /\bsrc="([^"]*)"/;
const TITLE_ATTRIBUTE = /\btitle="([^"]*)"/;

/** A name with "&" arrives as "&amp;" because it comes from inside HTML. */
function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&apos;/g, "'");
}
